### ISSUE TITLE
Referrer header?

### ISSUE THREAD

**Issue by Darker** [sub2u/vimeo-downloader#1]
I need to backup private videos. I need to send my website URL as referrer, othervise Vimeo will not show the video. Is there an option for that?

**Comment by sub2u** [comment]
Right now we won't support that.
I will let you know once we support that header.

**Comment by bonaccorsop** [comment]
I need to trap stream errors.
For example I have this error that I can't catch:

"ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

I have this code:

`
let stream = vidl(url, { quality: '360p', format: 'mp4' });

stream.on('error', (err) => {
    //I should to catch error here!!
    //It seems doesn't work
    console.error(err);    
});

stream.on('finish', () => {
    //Ok here, I launch my finish event.
});

stream.pipe(fs.createWriteStream(filename));
`

**Comment by sub2u** [comment]
You can pass your website as option

```
vidl(url, { quality: '360p', Referer: <Your website address> })
  .pipe(fs.createWriteStream('vide.mp4'));

```
